# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: abhishekorg
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: bountywise
# "service" is the name of this project. This will also be added to your AWS resource names.
service: bountywise-services

provider:
  name: aws
  runtime: nodejs20.x

functions:
  bounty-services:
    handler: services/bounty-services/handler.handler
    events:
      - httpApi: "*"
  tags-services:
    handler: services/tags-services/handler.handler
    events:
      - httpApi: "*"
